spring.application.name=credentials-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/credentials_store
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Optional: Makes logs cleaner
spring.output.ansi.enabled=ALWAYS

jwt.secret=changeThisToAStrongSecretKeyWithAtLeast32Characters